{% set name = "yarg" %}
{% set version = "0.1.10" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/kura/{{ name }}/archive/refs/tags/{{ version }}.tar.gz
  sha256: b3b8126bf305951e40242eb87e621125a8cf697bcfa4db7e164f6679fcbe0af7

build:
  number: 0
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  skip: True  # [py<3 or py>312]

requirements:
  host:
    - python
    - pip
    - wheel
    - setuptools
  run:
    - python
    - requests

test:
  source_files:
    - tests
  imports:
    - yarg
  commands:
    - pip check
    - python -c "from importlib.metadata import version; assert(version('{{ name }}')=='{{ version }}')"
    - pytest -v tests
  requires:
    - pip
    - pytest

about:
  home: https://yarg.readthedocs.org/
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: A semi hard Cornish cheese, also queries PyPI (PyPI client)
  description: A semi hard Cornish cheese, also queries PyPI. Built on top of requests, it’s easy to use and makes sense.
  dev_url: https://github.com/kura/yarg
  doc_url: https://yarg.readthedocs.io/

extra:
  recipe-maintainers:
    - proinsias
