travis:
  secure:
    BINSTAR_TOKEN: aXdZiu6aVyoAQ5Floc9u7PTsTbGwAq0kbKMdiEYcqC0xDUxok0oaD6im/O7WDpYkO0xW1R1im+oyXs3e0WB7LPYePq3kxCvDrvXtmnZNKEucyCN0hGHXhCbLC29TbkTKTqHASiXB/bf3oY5nhKcATHxf7S8juzzg1fe734kGCagII6mJ7shEfOj22bh26E/FNSJOzFmXS26i3oCrjb6DmKujOQ72Sm7QmcAUwvf5h+ZBKMOoAQou8Ny7603803+AX8M1hwy1hiZECoP9/F85krUOOYZ8hCc23sXq/rLfIy8o17GPEinO4Blrgbj8Z3ADmLp8jJ6DKg/qsH9SbfbW0xtmb/mAtzEw3KYth98wymLa873O3yQXgHYzvv9mblpHRfBieG2/C+dn7UxVPpniZoZhK/fb7Z8bzBeUyf3duqDEe60HdjgmT4EY5mSYkfXiUiaMFH9v+cfIvqoPQV0WnrmHzvkrg3IiWDVBrYcAe+vd88sarZeh3nx8kAaHGOKFULNLRgQXKhBAa+4lKSeBN1EPdLOxqddbVFZsYYumWR4t1FWZTyXdOY2P3KIHP70W9VX+6txKUubA3lV3kU0eY18dfQWD2vT+e6MpMDBJpn7WIsX44eDq+fV+KGrSID3Pdqj9kXDcyDL2DnCwomr06TEOABI/03RBIyhhez0Rc8c=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
