travis:
  secure:
    BINSTAR_TOKEN: dMU+oestjcdAkzFON5fjmf8wprGDqKFMABRwu1EHIG5Q1Ud2eP4pbsmco/Hjg3QEzkarmvT3nhD1V6bUNXxVwLav57Uuyiw8tP4qgwkm3W5VGUsgCrnkO+VTWLAxuBj1TeT5OgTHNW8O2gf/f3ozEcPVNf4lhfjwrpc/Le6OOmWQHwaqcbMa+I6Cf54lzaUV0082yfSl2V6a/VFGci6KaOiQEBuq42znwiHxZV+xyuQkLwkYGifa4vbQM1EoIDgDELuXygKdzhellPf41JMUbeXZtWPvcp4xH6+vqXtkJqxYH3V2FzNr8vSSmwCd8njpkqYx1KKQPW9zTYgVTOtvv93deOsjoRmUcx4qD2unGeg1qU0XxcWFdRqUiSevS8MbsyVYJ3c4xwsH7U6RFjFqlcmbC7nUxfUWW2+7wxmjuHU3gjZWYlXP791sb9DZgQKbW8V18T/uvfs7Z/ea2vnNVLUjuZIFTwQQ0OrT4uWYzCUz6KYtVxufozMHTDLew+8C67M4emAeHx3myO3AtbLftJfkPJNzSFJEQTxmxu30N4B4sk5A2epFNmdi52CEvDv472Ea7hhh0Zn7aH68TIpIy4fh1Otok1LCXPoMIXDlX6rIvO8Q+cMV9VFK+d11veI3/jEuTBTvLKiOSf9V/XXqJLr2rHg2i+4H4NFJpd5vw7o=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
conda_forge_output_validation: true
bot:
  automerge: true
