travis:
  secure:
    BINSTAR_TOKEN: jO+PZTfdrTtzQLq5OaLGgombREZwbyJI3ZUSkpuWThJr71uDJ1k/8jtYQ69PcjNAW7UWZ+6jwtTy8J8H8HXeNCvW0Bm4vhdLzE79YCT6+BAVL+qyh1KBy0uj73qU+3mkqiBNg9YlcfvpBXaaRjyghxew/Pn1kxTNbCLPqqf9PgqLr0TWyZzRNh8NhKraNGR7abTihPtDg3jNrEEFvCzfy//P0gG4SamoD595xAcHQJM0nd2EsG4tVZogLea8UHwR4glsdImx1WauxuSulb+1knhc6Vn9eyIqN5ctVDvIxKfVI2XcvgsIx02M04lEcpQFCjh7nzIxtOuzY8Pp6FjgPPclb7QKRGTaVE9w3UO7ol3amzTo8X4LPrLGYjqe4RmJpVS6uX4AQ0gLcpKks157QmRx/tLJDctUUg/HVtb82T9bQINjS4cFzIuj65nV9Q5TkWkUY37cDVzcfc0l/kaT2hL+3aN8SR8/GTPlbfqKP1Y4hocYIWOxcQqoW26QQtv89bY8Z7Wgth8B2BU020M8y1iezVHMlSNKKs3FCtoFfw3mdLQtPHNU6U48JImaP5Wa58WLqKAicwWAgCJ64N/Le8aQBCJdsVUoK11FxLABaDL/vh9cghzCTbqT4x0BZ5BKFyISGtdg2nOBQLhJrxsAS7oqTNTZTUkrA5Z8bPQS2ks=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
